//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ADFOpus.rc
//
#define IDS_VERSION                     1
#define IDD_ABOUT                       101
#define IDR_MAINMENU                    102
#define IDI_MAIN                        103
#define IDD_ABOUTPAGE1                  104
#define IDB_LOGO                        105
#define IDC_POINTER_COPY                105
#define IDD_ABOUTPAGE2                  106
#define IDD_NEWVOLUME                   107
#define IDI_WINFILE                     121
#define IDI_AMIFILE                     122
#define IDI_WINDIR                      124
#define IDI_AMIDIR                      125
#define IDI_WINLISTER                   126
#define IDB_TBBUTTONS                   158
#define IDD_VOLSELECT                   159
#define IDD_ABOUTPAGE3                  163
#define IDD_VOLINFOPAGE1                164
#define IDD_VOLINFOPAGE2                165
#define IDD_PROGRESS2                   166
#define IDD_PROGRESS1                   168
#define IDI_AMILISTER                   171
#define IDI_DRIVECD                     172
#define IDI_DRIVEFLOP35                 173
#define IDI_DRIVEFLOP514                174
#define IDI_DRIVEHD                     175
#define IDI_DRIVENET                    176
#define IDR_RDRAGMENU                   178
#define IDR_LISTERMENU                  179
#define IDD_VOLINFO                     180
#define IDD_BATCHCONVERTER              181
#define IDD_OPTIONS                     187
#define IDD_ABOUTPAGE4                  188
#define IDD_FILEPROPERTIES_WIN          189
#define IDD_ABOUTPAGE5                  190
#define IDD_ABOUTPAGE6                  191
#define IDI_ICON_ADF                    194
#define IDI_ICON_ADZ                    195
#define IDI_ICON_DMS                    196
#define IDI_ICON_DMP                    197
#define IDI_ICON_HDF                    198
#define IDD_FILEPROPERTIES_AMI          202
#define IDD_DISK2FDI                    203
#define IDD_DISPLAY_BOOTBLOCK           204
#define IDB_NEW                         206
#define IDB_OPEN                        207
#define IDB_CLOSE                       208
#define IDB_RENAME                      209
#define IDB_DELETE                      210
#define IDB_CREATEDIR                   211
#define IDB_UPONELEVEL                  212
#define IDB_INFO                        213
#define IDB_PROPERTIES                  214
#define IDB_OPTIONS                     215
#define IDB_BATCH                       216
#define IDB_DISK2FDI                    217
#define IDB_INSTALL                     218
#define IDB_DISPLAY                     219
#define IDB_TILEHOR                     220
#define IDB_TILEVER                     221
#define IDB_CASCADE                     222
#define IDB_HELP                        223
#define IDB_ABOUT                       224
#define IDB_UNDELETE                    225
#define IDB_SHOWUNDELETABLE             226
#define IDB_TEXTVIEWER                  227
#define IDD_TEXT_VIEWER                 228
#define IDD_GREASEWEAZLE                229
#define IDD_GREASEWEAZLE_WRITEFLOPPY    230
#define IDD_GREASEWEAZLE_WRITE          231
#define IDD_HEX_FILE_VIEWER             232
#define IDD_HEX_VIEWER                  233
#define IDC_NEWPATH                     1004
#define IDC_NEWADF                      1005
#define IDC_NEWHARDFILE                 1006
#define IDC_NEWPRESET                   1007
#define IDC_NEWCUSTOM                   1008
#define IDC_NEWCUSTOMSIZE               1009
#define IDC_NEWPRESETSIZE               1010
#define IDC_NEWHD                       1011
#define IDC_NEWFFS                      1012
#define IDC_NEWINTL                     1013
#define IDC_NEWLABEL                    1014
#define IDC_NEWHELP                     1016
#define IDC_VOLSELOPEN                  1017
#define IDC_OOK                         1017
#define IDC_ZLIBBTN                     1017
#define IDC_VOLINFO_HELP                1018
#define IDC_OREGISTER                   1018
#define IDC_VOLSELLIST                  1025
#define IDC_ABOUTTABCTRL                1026
#define IDC_TOTALPROGRESS               1028
#define IDC_CURFILEPROGRESS             1029
#define IDC_VOLLABEL                    1030
#define IDC_OLABEL                      1030
#define IDC_NEWDIRC                     1031
#define ID_LOGO                         1032
#define IDC_CREATEPROGRESS              1033
#define IDC_CURRENTFILE                 1034
#define IDC_NEWBROWSE                   1035
#define IDC_NEWCREATE                   1036
#define IDC_NEWPRESETSLIDER             1039
#define IDC_NEWBOOTABLE                 1040
#define IDC_VOLINFOTABCTRL              1041
#define IDC_WEBPAGEBTN                  1042
#define IDC_EMAILBTN                    1043
#define IDC_DEVSIZE                     1044
#define IDC_DEVPATH                     1045
#define IDC_DEVTYPE                     1046
#define IDC_DEVCYLINDERS                1047
#define IDC_DEVHEADS                    1048
#define IDC_DEVSECT                     1049
#define IDC_BCREMOVEALL                 1050
#define IDC_OHELP                       1050
#define IDC_BCADF                       1051
#define IDC_ODRIVELIST                  1051
#define IDC_BCADZ                       1052
#define IDC_OTHISDIR                    1052
#define IDC_BCSTATUS                    1053
#define IDC_BCSTART                     1054
#define IDC_BCHELP                      1055
#define IDC_DEVVOLLIST                  1058
#define IDC_BCFILELIST                  1059
#define IDC_BCADD                       1060
#define IDC_BCREMOVE                    1061
#define IDC_VOLFFS                      1062
#define IDC_VOLINTL                     1063
#define IDC_VOLDIRC                     1064
#define IDC_VOLTOTAL                    1065
#define IDC_VOLUSED                     1066
#define IDC_VOLFREE                     1067
#define IDC_VOLFULL                     1068
#define IDC_VOLFULLGAUGE                1069
#define IDC_VOLSELHELP                  1070
#define IDC_ODELETE                     1071
#define IDC_ODELDIR                     1072
#define IDC_ODIR                        1073
#define IDC_ADFLIBVER                   1074
#define IDC_ODIRCACHE                   1075
#define IDC_ADFLIBDATE                  1075
#define IDC_CURRENTSECTOR               1076
#define IDC_ADFLIBBTN                   1077
#define IDC_OAPPLY                      1078
#define IDC_NEWOPEN                     1079
#define IDC_AMI_READABLE                1081
#define IDC_AMI_WRITABLE                1082
#define IDC_AMI_EXECUTABLE              1083
#define IDC_AMI_DELETABLE               1084
#define IDC_AMI_SCRIPT                  1085
#define IDC_AMI_ARCHIVE                 1086
#define IDC_WIN_READONLY                1089
#define IDC_WIN_ARCHIVE                 1090
#define IDC_WIN_HIDDEN                  1091
#define IDC_WIN_SYSTEM                  1092
#define IDC_PROPERTIES_WIN_HELP_BUTTON  1093
#define IDC_AMI_PURE                    1094
#define IDC_AMI_HOLDBIT                 1095
#define IDC_OPUS_VERSION                1096
#define IDC_PROPERTIES_FILENAME_WIN     1097
#define IDC_PROPERTIES_AMI_HELP_BUTTON  1098
#define IDC_PROPERTIES_FILENAME_AMI     1099
#define IDC_EDIT_COMMENT                1100
#define IDC_PROPERTIES_AMI_OK_BUTTON    1101
#define IDC_PROPERTIES_WIN_OK_BUTTON    1102
#define IDC_RADIO_FDI                   1103
#define IDC_RADIO_ADF                   1104
#define IDC_CHECK_SECTORS               1106
#define IDC_RADIO_ST                    1107
#define IDC_RADIO_IMG                   1108
#define IDC_SPIN_SECTORS                1110
#define IDC_EDIT_SECTORS                1111
#define IDC_EDIT_FILENAME               1112
#define IDC_CHECK_USE_B_DRIVE           1114
#define IDC_RADIO_SINGLE_SIDED          1115
#define IDC_RADIO_DOUBLE_SIDED          1116
#define IDC_CHECK_TRACKS                1117
#define IDC_EDIT_TRACKS                 1118
#define IDC_SPIN_TRACKS                 1119
#define IDC_BUTTON_FDI_HELP             1121
#define IDSTART                         1123
#define IDC_EDIT_BOOTBLOCK              1127
#define IDC_BOOTBLOCK_HELP              1128
#define IDC_ZLIBVER                     1129
#define IDC_STATIC_SECTORS              1130
#define IDC_STATIC_HEADS                1131
#define IDC_STATIC_CYLINDERS            1132
#define IDC_STATIC_TYPE                 1133
#define IDC_STATIC_SIZE                 1134
#define IDC_STATIC_PATH                 1135
#define IDC_CHECK_OPEN                  1136
#define IDC_BCDELETE_ORIGINAL           1137
#define IDC_EDIT_TEXT                   1138
#define IDC_TEXTVIEWER_HELP             1139
#define IDC_HOTKEY1                     1140
#define IDC_WEBPAGEBTN2                 1141
#define IDGWSTART                       1141
#define IDC_GW_EDIT_FILENAME            1142
#define IDC_GW_CHECK_OPEN               1143
#define IDC_GW_RADIO_ADF                1144
#define IDC_GW_CHECK_USE_DRIVE_0        1145
#define IDC_STATIC_GW_DENSITY           1146
#define IDC_GW_RADIO_DOUBLEDENSITY      1147
#define IDC_GW_RADIO_HIGHDENSITY        1148
#define IDC_GW_CHECK_USE_DRIVE_1        1149
#define IDC_GW_RADIO_HIGHDENSITY2       1149
#define IDC_GW_STATIC_READWRITE         1150
#define IDC_GW_SELECTED_READ            1151
#define IDC_GW_SELECTED_WRITE           1152
#define IDC_GW_RADIO_ADF2               1153
#define IDC_RADIO1                      1154
#define IDC_GW_RADIO_DRIVE_0            1154
#define IDC_GW_RADIO_DRIVE_A            1154
#define IDC_GW_RADIO_WRITE_DRIVE_A      1154
#define IDC_RADIO2                      1155
#define IDC_GW_RADIO_DRIVE_1            1155
#define IDC_GW_RADIO_DRIVE_B            1155
#define IDC_GW_RADIO_WRITE_DRIVE_B      1155
#define IDC_RADIO3                      1156
#define IDC_GW_RADIO_READ_IMAGE         1156
#define IDC_RADIO4                      1157
#define IDC_GW_RADIO_WRITE_IMAGE        1157
#define IDC_RADIO5                      1158
#define IDC_RADIO6                      1159
#define IDC_GW_RADIO_ADZ                1159
#define IDC_GW_EDIT_PATH                1160
#define IDC_GW_NEWBROWSE                1161
#define IDC_GW_BTN_BROWSE               1161
#define IDC_GW_COMBO_FILETOWRITE        1163
#define IDC_BUTTON2                     1165
#define ID_CANCEL_GW_WRITE              1165
#define ID_GW_WRITE_CANCEL              1165
#define IDC_BOOTBLOCK_SAVEBINARY        1165
#define IDC_BTN_OK                      1165
#define IDC_GW_SHOWDENSITY              1166
#define ID_GW_WRITE_START               1167
#define IDC_BOOTBLOCK_COPY              1169
#define IDC_EDIT_HEX                    1171
#define IDC_BOOTBLOCK_SAVETEXT          1172
#define IDC_BUTTON1                     1173
#define IDC_BTN_CREDITS                 1173
#define IDC_BTN_WEBSITE                 1174
#define IDC_STATIC_BUILD                1175
#define ID_ACTION_NEWDIRECTORY          40001
#define ID_ACTION_RENAME                40002
#define ID_ACTION_DELETE                40003
#define ID_ACTION_PROPERTIES            40004
#define ID_FIL_EXIT                     40006
#define ID_HELP_ABOUT                   40007
#define ID_EDIT_SELECTALL               40008
#define ID_EDIT_SELECTNONE              40009
#define ID_EDIT_INVERTSELECTION         40010
#define ID_VIEW_REFRESH                 40013
#define ID_FIL_INFORMATION              40018
#define ID_TOOLS_OPTIONS                40020
#define ID_WIN_TILEHORIZONTAL           40022
#define ID_WIN_ARRANGEICONS             40023
#define ID_HELP_HELPTOPICS              40025
#define ID_HELP_MAIN                    40026
#define ID_WIN_TILEVERTICAL             40028
#define ID_WIN_CASCADE                  40030
#define ID_ACTION_UPONELEVEL            40068
#define ID_VIEW_NEWWINDOWSLISTER        40069
#define ID_WIN_CLOSEALL                 40070
#define ID_FIL_OPENDEVICE               40071
#define ID_VIEW_TOOL_BAR                40072
#define ID_VIEW_THE_STATUSBAR           40073
#define ID_FIL_NEW                      40074
#define ID_FIL_OPEN                     40075
#define ID_FIL_CLOSE                    40076
#define ID_TOOLS_BATCHCONVERTER         40077
#define ID_TOOLS_INSTALL                40078
#define ID_VIEW_CLONECURRENTWINDOW      40079
#define ID_COPY                         40080
#define ID_MOVE                         40081
#define ID_LINK                         40082
#define ID_TOOLS_DISK2FDI               40095
#define ID_TOOLS_DISPLAYBOOTBLOCK       40098
#define ID_BUTTON40099                  40099
#define ID_BUTTON40100                  40100
#define ID_BUTTON40101                  40101
#define ID_BUTTON40102                  40102
#define ID_BUTTON40103                  40103
#define ID_BUTTON40104                  40104
#define ID_BUTTON40105                  40105
#define ID_BUTTON40106                  40106
#define ID_BUTTON40107                  40107
#define ID_BUTTON40111                  40111
#define ID_BUTTON40113                  40113
#define ID_BUTTON40114                  40114
#define ID_BUTTON40117                  40117
#define ID_BUTTON40119                  40119
#define ID_VIEW_SHOWUNDELETABLEFILES    40120
#define ID_ACTION_UNDELETE              40121
#define ID_BUTTON40123                  40123
#define ID_BUTTON40124                  40124
#define ID_BUTTON40125                  40125
#define ID_TOOLS_TEXT_VIEWER            40126
#define IDC_LICENCEPAGEBTN              40127
#define ID_Menu                         40127
#define IDB_TBBUTTONS_LARGE             40128
#define ID_Menu40128                    40128
#define IDC_BUILDINFO                   40129
#define ID_TOOLS_HEXVIEWER              40129
#define IDB_TBBUTTONS_TRUECOLOR         40130
#define ID_TOOLS_HEX_VIEWER             40130
#define IDB_TILECLO                     40131
#define ID_SEL_HEXVIEWER                40131
#define IDB_REFRESH                     40132
#define ID_TOOLS_WRITE_RAW_BOOTBLOCK    40132
#define ID_SEL_SELECTINVERTED           40133
#define IDB_SELECTALL                   40134
#define ID_Menu40134                    40134
#define IDB_SELECTNONE                  40135
#define IDM_HELP_README                 40135
#define IDB_INVERTSELECTION             40136
#define ID_TOOLS_GREASEWEAZLE           40137
#define IDB_GREASEWEAZLE                40138
#define ID_TOOLS_GREASEWEAZLEWRITE      40139
#define IDB_GREASEWEAZLEWRITE           40140
#define IDB_HEXVIEWER                   40141
#define IDB_RAWWRITEBOOTBLOCK           40142
#define IDC_UPDATELABEL                 40143
#define IDB_EXIT                        40144
#define IDB_NEWLIST                     40145
#define IDB_TOOLS_WRITE_RAW_BOOTBLOCK   40146
#define IDB_NEW_ABOUT_GRAPHIC           40147
#define IDC_NEW_ABOUT_GRAPHIC           40148
#define IDB_README                      40149
#define IDC_STATIC                      -1

#define IDI_NEW                 50001
#define IDI_NEWLIST             50002
#define IDI_OPEN                50003
#define IDI_CLOSE               50004
#define IDI_EXIT                50005
#define IDI_RENAME              50006
#define IDI_DELETE              50007
#define IDI_CREATEDIR           50008
#define IDI_UPONELEVEL          50009
#define IDI_INFO                50010
#define IDI_PROPERTIES          50011
#define IDI_OPTIONS             50012
#define IDI_BATCH               50013
#define IDI_GREASEWEAZLE        50014
#define IDI_GREASEWEAZLEWRITE   50015
#define IDI_INSTALL             50016
#define IDI_RAWWRITEBOOTBLOCK   50017
#define IDI_DISPLAY             50018
#define IDI_TILEHOR             50019
#define IDI_TILEVER             50020
#define IDI_CASCADE             50021
#define IDI_TILECLO             50022
#define IDI_HELP                50023
#define IDI_ABOUT               50024
#define IDI_UNDELETE            50025
#define IDI_SHOWUNDELETABLE     50026
#define IDI_REFRESH             50027
#define IDI_TEXTVIEWER          50028
#define IDI_HEXVIEWER           50029
#define IDI_TBBUTTONS_TRUECOLOR 50030
#define IDI_SELECTALL           50031
#define IDI_SELECTNONE          50032
#define IDI_INVERTSELECTION     50033
#define IDI_README              50034


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        240
#define _APS_NEXT_COMMAND_VALUE         40136
#define _APS_NEXT_CONTROL_VALUE         1177
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
